Fix for Issue 1834: Performance degradation caused by high CPU usage when Promitor-agent-scraper has to scrape large set of Azure targets
tomkerkhove/promitor pull request #2043
Opened 2022-06-07 15:59 UTC by jasonmowry

Revise Promitor scraper task scheduling to organize Cron jobs by schedule instead of resource parameters, then handle multiple resources and/or resource discovery groups per job. Optionally enforce maximum degree of parallelism across all Cron jobs using a mutex shared across the jobs where each operation that requires network access to interact with the cluster is run on the thread pool and each counts as 1 against the degree of parallelism.

Fixes #1834

2022-06-07 15:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tomkerkhove/promitor?pullRequest=2043) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tomkerkhove/promitor?pullRequest=2043) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tomkerkhove/promitor?pullRequest=2043) it.</sub>

2022-06-08 09:21 UTC, tomkerkhove commented on src/Promitor.Tests.Unit/Generators/Config/BogusScraperRuntimeConfigurationGenerator.cs
> +                .RuleFor(srvConfig => srvConfig.MaxDegreeOfParallelism, faker => faker.Random.Int())
Can you add a unit test for this please?

2022-06-09 11:22 UTC, tomkerkhove requested changes
Did a first run of review - Thanks a ton for this!

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
> +                                await ScheduleLimitedConcurrencyAsyncTask(tasks, () => GetDiscoveryGroupScrapeDefinitions(resourceDiscoveryGroup.Name, metric, scrapeDefinitions), cancellationToken);
Let's add {}

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
> +                                GetResourceScrapeDefinition(resourceDefinition, metric, scrapeDefinitions);
Let's add {}

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
> +                    scrapeDefinitions.Add(metricDefinition.CreateScrapeDefinition(discoveredResource, _metricsDeclaration.AzureMetadata));
Let's not inline this creation

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
> +            scrapeDefinitions.Add(metricDefinition.CreateScrapeDefinition(resourceDefinition, _metricsDeclaration.AzureMetadata));
Let's not inline this creation

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Core.Scraping/Configuration/Model/MetricDimension.cs
> +        #region Equality
Please remove the region

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Core.Scraping/Configuration/Model/MetricDimension.cs
> +            if (ReferenceEquals(null, other))
Never saw ReferenceEquals before, where is this coming from?

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Core.Scraping/Configuration/Model/MetricDimension.cs
> +        public bool Equals(MetricDimension other)
Can we add tests for this?

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Core.Scraping/Configuration/Model/Scraping.cs
> +        public bool Equals(Scraping other)
Can we add tests for this?

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Core.Scraping/Configuration/Model/Scraping.cs
> +        #region Equality
Please remove

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Scheduling/SchedulingExtensions.cs
> +                scheduleDescription = CronExpressionDescriptor.ExpressionDescriptor.GetDescription(metricsDeclaration.Metrics[0].Scraping.Schedule);
What does this do?

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Scheduling/SchedulingExtensions.cs
> +            return $"PromitorScraper-{metricsCount}Metrics-{scheduleDescription}-{uniqueness}";
```suggestion
            return $"Scraper-{metricsCount}Metrics-{scheduleDescription}-{uniqueness}";
```

2022-06-09 11:22 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Scheduling/SchedulingExtensions.cs
> +                        schedulerOptions.CronSchedule = metricsDeclaration.Metrics[0].Scraping.Schedule;
Why are we changing this?

2022-06-09 22:26 UTC, MattiasAng commented
Hope you don't mind that I made som suggestions as well @tomkerkhove and @jasonmowry. Found a few issues while testing, and we really want this one merged to help the issues we are running in to as well.

2022-06-10 13:00 UTC, tomkerkhove commented
> Hope you don't mind that I made som suggestions as well @tomkerkhove and @jasonmowry. Found a few issues while testing, and we really want this one merged to help the issues we are running in to as well.

No worries at all but make sure to publish them as I don't see it. If it's outside of the scope of this PR, feel free to open an issue.

2022-06-10 19:33 UTC, MattiasAng requested changes

2022-06-10 19:34 UTC, MattiasAng commented
> No worries at all but make sure to publish them as I don't see it. If it's outside of the scope of this PR, feel free to open an issue.

That's what you get when working late.

2022-06-16 06:49 UTC, tomkerkhove commented
@jasonmowry Just checking - Can I help you on this PR or are you good for now?

2022-06-16 23:53 UTC, jasonmowry commented
Closing this PR and replacing with https://github.com/tomkerkhove/promitor/pull/2050 to correct last commit which was mistakenly pushed with wrong author account.

2022-06-16 23:53 UTC, closed without merging