Adding ability to define a custom AzureEnvironment.
tomkerkhove/promitor pull request #2579
Opened 2024-11-25 23:42 UTC by kevand900

Add support for a custom azure environment whose endpoints can be defined via environment variables in a helm values file. This creates the ability to deploy to new regions without requiring code changes.

2024-11-25 23:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tomkerkhove/promitor?pullRequest=2579) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tomkerkhove/promitor?pullRequest=2579) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tomkerkhove/promitor?pullRequest=2579) it.</sub>

2024-11-29 07:50 UTC, tomkerkhove requested changes
Thanks! However, let's move it to the configuration rather than ENV VAR.

2024-11-29 07:50 UTC, tomkerkhove commented on src/Promitor.Core/Extensions/AzureCloudExtensions.cs
> +                    return new Uri(Environment.GetEnvironmentVariable("PROMITOR_AZURE_AUTH_ENDPOINT"));
Let's not do this but move it to the YAML configuration instead please

2024-11-29 07:50 UTC, tomkerkhove commented on src/Promitor.Core/Extensions/AzureEnvironmentExtensions.cs
> +            KeyVaultSuffix = Environment.GetEnvironmentVariable("PROMITOR_KEY_VAULT_SUFFIX")
Same here, let's move this to the YAML configuration instead

2025-01-10 03:24 UTC, kevand900 commented on src/Promitor.Core/Extensions/AzureCloudExtensions.cs
> +                    return new Uri(Environment.GetEnvironmentVariable("PROMITOR_AZURE_AUTH_ENDPOINT"));
@tomkerkhove, do you have an example how this is used elsewhere? An existing YAML config file or create new?

2025-01-13 06:45 UTC, tomkerkhove commented on src/Promitor.Core/Extensions/AzureCloudExtensions.cs
> +                    return new Uri(Environment.GetEnvironmentVariable("PROMITOR_AZURE_AUTH_ENDPOINT"));
All the configuration is based on YAML configuration, by not reading from environment variable but configuration instead

2025-01-16 20:22 UTC, Suraiya-Hameed commented on src/Promitor.Core/Extensions/AzureCloudExtensions.cs
> +                    return new Uri(Environment.GetEnvironmentVariable("PROMITOR_AZURE_AUTH_ENDPOINT"));
I've updated the PR to read from existing runtime.yaml config, @tomkerkhove PTAL

runtime.yaml
```yaml
..
azureCustomCloud:
  authenticationEndpoint: <>
  resourceManagerEndpoint: <>
  graphEndpoint: <>
  managementEndpoint: <>
  storageEndpointSuffix: <>
  keyVaultSuffix: <>
```

2025-01-21 17:50 UTC, Suraiya-Hameed commented
@tomkerkhove can you please review this PR again? I can open a PR in docs repo if this looks good

2025-01-22 06:59 UTC, tomkerkhove commented
/azp run "Promitor CI - Scraper Agent"

2025-01-22 07:59 UTC, tomkerkhove commented
Can you please sign off the CLA?

2025-01-24 06:47 UTC, tomkerkhove commented on src/Promitor.Core/Extensions/AzureCloudExtensions.cs
> +                    return new Uri(Environment.GetEnvironmentVariable("PROMITOR_AZURE_AUTH_ENDPOINT"));
This isn't really consistent; can we just add these under the existing `azureMetadata` please?
https://docs.promitor.io/latest/scraping/overview/#example

Given you are adding endpoints, let's just go with `azureMetadata.endpoints.<name>` so those can be overridden

2025-01-24 17:49 UTC, Suraiya-Hameed commented on src/Promitor.Core/Extensions/AzureCloudExtensions.cs
> +                    return new Uri(Environment.GetEnvironmentVariable("PROMITOR_AZURE_AUTH_ENDPOINT"));
I added them in runtime.yaml as both scraper and resource discovery components have it and these values are needed by both. 

Moving them under `azureMetadata.endpoints` for scraper seems like a better place, then for resource discover should we have them under `azureLandscape.endpoints` ?

2025-01-24 19:15 UTC, tomkerkhove commented on src/Promitor.Core/Extensions/AzureCloudExtensions.cs
> +                    return new Uri(Environment.GetEnvironmentVariable("PROMITOR_AZURE_AUTH_ENDPOINT"));
Sounds good, thanks!

2025-01-29 19:40 UTC, Suraiya-Hameed commented on src/Promitor.Core/Extensions/AzureCloudExtensions.cs
> +                    return new Uri(Environment.GetEnvironmentVariable("PROMITOR_AZURE_AUTH_ENDPOINT"));
@tomkerkhove PTAL at the updates

I haven't added code for deserialization(AzureMetadataDeserializer.cs) of `endpoints` in AzureMetadataV1, as it seems to work only for AzureCloud.Global,  AzureCloud.UsGov and AzureCloud.China

2025-02-03 15:48 UTC, tomkerkhove commented on src/Promitor.Agents.ResourceDiscovery/Configuration/AzureLandscape.cs
> +        public AzureEnvironment? AzureEnvironment { get; set; }
Let's stick with using Cloud by default and not mutate in validation logic; but when endpoints is specified us that over cloud and its respective environment

2025-02-03 15:48 UTC, tomkerkhove commented on src/Promitor.Agents.ResourceDiscovery/Graph/AzureResourceGraph.cs
> +            var azureEnvironment = _resourceDeclarationMonitor.CurrentValue.AzureLandscape.AzureEnvironment;
See comment above

2025-02-03 15:48 UTC, tomkerkhove commented on src/Promitor.Agents.ResourceDiscovery/Validation/Steps/AzureLandscapeValidationStep.cs
> +        private IEnumerable<string> ValidateAzureCloudEnvironment()
We can reduce this to just validate _azureLandscape.AzureEnvironment's properties when it is not null. In that case they should all be provided

2025-02-03 15:48 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
> +                    AzureAuthenticationFactory.GetConfiguredAzureAuthentication(_configuration), new Uri(_metricsDeclaration.AzureMetadata.AzureEnvironment.AuthenticationEndpoint));
Probably we need a GetAzureEnvironment for AzureMetadata that has the logic to favor custom over cloud config

2025-02-03 15:48 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Validation/Steps/MetricsDeclarationValidationStep.cs
> +        private static IEnumerable<string> ValidateAzureCloudEnvironment(AzureMetadata azureMetadata)
Same comment here

2025-02-03 15:48 UTC, tomkerkhove commented on src/Promitor.Core.Scraping/Configuration/Model/AzureMetadata.cs
> +        [JsonPropertyName("endpoints")]
We should not need this, only on serialization models

2025-02-06 13:46 UTC, tomkerkhove commented on src/Promitor.Agents.ResourceDiscovery/Validation/Steps/AzureLandscapeValidationStep.cs
> +            }
Let's validate per endpoint to have proper/more efficient error reporting

2025-02-06 13:46 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
> +                var azureEnvironent = _metricsDeclaration.AzureMetadata.Cloud.GetAzureEnvironment(_metricsDeclaration.AzureMetadata.Endpoints);
Instead of passing this everywhere, we should change it to something like this:
```suggestion
                var azureEnvironent = _metricsDeclaration.AzureMetadata.GetAzureEnvironment();
```

2025-02-06 13:46 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Validation/Steps/MetricsDeclarationValidationStep.cs
> +            else if (string.IsNullOrWhiteSpace(azureMetadata.Endpoints.AuthenticationEndpoint) ||
Same here

2025-02-06 13:46 UTC, tomkerkhove commented on src/Promitor.Core.Scraping/Configuration/Serialization/v1/Core/AzureEndpointsDeserializer.cs
> +                .MapUsing(ValidateUrl); // Should this be required?
Does SDK provide it by default? If so, then yes.

2025-02-07 00:50 UTC, Suraiya-Hameed commented on src/Promitor.Agents.Scraper/Scheduling/ResourcesScrapingJob.cs
> +                var azureEnvironent = _metricsDeclaration.AzureMetadata.Cloud.GetAzureEnvironment(_metricsDeclaration.AzureMetadata.Endpoints);
I've updated the code accordingly, except for the calls made to methods in `Promitor.Integrations.AzureMonitor`. These methods currently do not reference `Promitor.Core.Scraping.Configuration.Model.AzureMetadata`, and adding this reference would introduce a circular dependency, as the flow of dependencies currently goes from `Promitor.Core.Scraping` to `Promitor.Integrations.AzureMonitor`.

2025-02-07 12:09 UTC, tomkerkhove commented on src/Promitor.Agents.ResourceDiscovery/Extensions/AzureLandscapeExtensions.cs
> +        public static Uri GetAzureAuthorityHost(this AzureLandscape azureLandscape) => azureLandscape.Cloud.GetAzureAuthorityHost(azureLandscape.Endpoints);
Let's not do this and instead move the existing extensions to the level of Azure Landscape

2025-02-07 12:09 UTC, tomkerkhove commented on src/Promitor.Agents.Scraper/Extensions/AzureMetaDataExtensions.cs
> +        public static Uri GetAzureAuthorityHost(this AzureMetadata azureMetadata) => azureMetadata.Cloud.GetAzureAuthorityHost(azureMetadata.Endpoints);
Same here. If the fact that there are 2 types is the problem, then let's get an interfact out of that for `Cloud`+`Endpoints` and create the extension based on that

2025-02-12 09:36 UTC, tomkerkhove approved these changes

2025-02-12 09:36 UTC, tomkerkhove commented on src/Promitor.Core/Extensions/AzureEnvironmentExtensions.cs
> +            return new AzureEnvironment
I presume they don't have a log analytics endpoint we can leverage instead?

2025-02-12 09:36 UTC, tomkerkhove commented on src/Promitor.Tests.Unit/Validation/Scraper/Metrics/ResourceTypes/LogAnalyticsDeclarationValidationStepsTests.cs
> +        public void LogAnalyticsDeclaration_CustomCloudWithoutLogAnalyticsEndpoint_Fails()
Let's add one where we do _not_ add log analytics and not specify endpoint; should pass

2025-02-12 15:25 UTC, Suraiya-Hameed commented on src/Promitor.Core/Extensions/AzureEnvironmentExtensions.cs
> +            return new AzureEnvironment
yes, AzureEnvironment doesn't have it

2025-02-12 19:08 UTC, tomkerkhove approved these changes

2025-02-12 19:08 UTC, tomkerkhove commented
/azp run

2025-02-12 19:08 UTC, tomkerkhove commented
Thanks a ton!!

2025-02-12 19:42 UTC, merged